AWSTemplateFormatVersion: "2010-09-09"
Description: |
  This template creates an EC2 with SSH 

Resources:
  AbdullahInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01c647eace872fc02
      InstanceType: t2.micro
      KeyName: firstkey
      UserData: 
        Fn::Base64: |
          #! /bin/bash
          yum update -y
          yum install -y httpd
          FOLDER="https://raw.githubusercontent.com/abdullahyalcin/101-kittens-carousel-static-website-ec2/main/static-web"
          cd /var/www/html
          wget ${FOLDER}/index.html
          wget ${FOLDER}/cat0.jpg
          wget ${FOLDER}/cat1.jpg
          wget ${FOLDER}/cat2.jpg
          wget ${FOLDER}/cat3.png
          systemctl start httpd
          systemctl enable httpd
      SecurityGroups: 
        - !Ref ApoInstanceSG
      Tags: 
        - Key: Name
          Value: ApoCFNInstance
        - Key: Environment
          Value: Dev    
  ApoInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows SSH and HTTP # Required
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0       
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0